### ISSUE TITLE
未找到对 API /getFolder 对请求

### ISSUE THREAD

**Issue by chunibyo-wly** [PointStoneTeam/mirrors.cug.edu.cn-web#5]
1. 我想修复 Folder 页面日期不等宽的问题, 然后在源码中没有找到相关代码
![image](https://user-images.githubusercontent.com/33208530/98399553-85b33280-209d-11eb-806a-5b3abda7a6a2.png)

2. 我测试了后端`API /getFolder`, 可以正常返回数据
![image](https://user-images.githubusercontent.com/33208530/98399754-daef4400-209d-11eb-9096-7988c96f010a.png)

3. 但是我发现 mock server 返回的是一个页面, 所以请问线上到文件夹功能是第三方服务吗
![image](https://user-images.githubusercontent.com/33208530/98399847-040fd480-209e-11eb-8ef0-f8b2015d1af5.png)

**Comment by cugxuan** [comment]
> 1. 我想修复 Folder 页面日期不等宽的问题, 然后在源码中没有找到相关代码
>    ![image](https://user-images.githubusercontent.com/33208530/98399553-85b33280-209d-11eb-806a-5b3abda7a6a2.png)
> 2. 我测试了后端`API /getFolder`, 可以正常返回数据
>    ![image](https://user-images.githubusercontent.com/33208530/98399754-daef4400-209d-11eb-9096-7988c96f010a.png)
> 3. 但是我发现 mock server 返回的是一个页面, 所以请问线上到文件夹功能是第三方服务吗
>    ![image](https://user-images.githubusercontent.com/33208530/98399847-040fd480-209e-11eb-8ef0-f8b2015d1af5.png)

你好，后端现在使用的是 [caddy](https://github.com/caddyserver/caddy) 提供文件服务的，我刚刚看了一下最新版的 caddy 也是有这个问题的、可能需要给他们提交 PR，或者等待他们修改。**这应该是因为没用等宽字体的原因**。

如果你想测试的话，下载 caddy 最新版，然后创建配置文件 `Caddyfile`，输入一下内容，注意修改路径
```
:2020 {
    root * /Users/xuan/go
    file_server browse
}
```
然后命令行执行 `$ ./caddy run --watch` 就可以在 `localhost:2020` 看到对应的前端效果了。
